name: GitHub Notification Digest

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

permissions:
  contents: read # access to check out code and install dependencies

jobs:
  send_digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: pip install --break-system-packages -r requirements.txt
      - name: Run digest script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
        run: python .github/scripts/digest.py

